name: Deploy mke App

on:
  push:
    branches:
      - main 
      - dev 
      - staging
    paths:
      - frontend/**
    
jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: frontend/dist

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build React app
        run: |
          cd frontend
          npm run build


      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION
  
      - name: Set Bucket Name based on Branch
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            BUCKET_NAME=$BUCKET_NAME
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            BUCKET_NAME=$BUCKET_NAME
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            BUCKET_NAME=$BUCKET_NAME
          else
            echo "Branch not configured for deployment."
            exit 1
          fi
      
      
      - name: Deploy to s3
        run: |
          aws s3 sync ./frontend/dist/ s3://mke-verein.de/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: $AWS_REGION
       
        


  Invalidate-CloudFront-cache:
    needs: setup-and-deploy
    runs-on: ubuntu-latest
    steps:
      
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION

      - name: Set Distribution ID
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            DISTRIBUTION_ID=$DISTRIBUTION_ID
          elif [ "${{ github.ref }}" == "refs/heads/staging" ]; then
            DISTRIBUTION_ID=$DISTRIBUTION_ID
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            DISTRIBUTION_ID=$DISTRIBUTION_ID
          else
            echo "Branch not configured for deployment."
            exit 1
          fi

      - name: Invalidate CloudFront
        run: |
          export AWS_PAGER=""
          aws cloudfront create-invalidation \
          --distribution-id $DISTRIBUTION_ID \
          --paths "/*"
        env:
          DISTRIBUTION: $DISTRIBUTION_ID
          PATHS: "/*"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}